### ISSUE TITLE
Simple classification example using pytorch(icevison)

### ISSUE THREAD

**Issue by TheGreyDiamond** [robmarkcole/fire-detection-from-images#14]
Hello, would you be able to provide an example which takes an image as input and returns is there is fire and where? Using pre-trained models.

**Comment by robmarkcole** [comment]
Hi @TheGreyDiamond this is not possible with my current data set as it does not include 'not a fire' images. However you could choose one of the listed data sets in the main readme and follow https://github.com/robmarkcole/fire-detection-from-images/tree/master/pytorch/classifier 
I may get around to this myself but it is a low priority
