### ISSUE TITLE
'Detections' object has no attribute 'imgs'

### ISSUE THREAD

**Issue by Young-GG** [robmarkcole/fire-detection-from-images#39]
when I run the code , got this error, could U tell me hoe to solve 
![图片](https://user-images.githubusercontent.com/93699131/194696864-7fa01191-948f-4809-9353-29d6432d5a95.png)
![图片](https://user-images.githubusercontent.com/93699131/194696877-5efa36c7-fa42-4c01-b08f-5b90c5a9b99b.png)

**Comment by robmarkcole** [comment]
Code needs updating, see https://github.com/robmarkcole/yolov5-flask/issues/23
